displayFullLangName: true
author: "Look Scanned"
ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowFullTextinRSS: true
ShowWordCount: true
socialIcons:
  - name: other
    title: Look Scanned
    url: "https://lookscanned.io"
  - name: github
    title: Github
    url: "https://github.com/lookscanned"
  - name: email
    title: Contact me via email
    url: "mailto:contact@lookscanned.io"
  - name: rss
    title: RSS
    url: "index.xml"
editPost:
  URL: "https://github.com/lookscanned/lookscanned-blog/blob/main/content"
  appendFilePath: true # to append file path to Edit link
ShowCodeCopyButtons: true
assets:
  favicon: "/favicon.ico"
  favicon16x16: "/favicon-16x16.png"
  favicon32x32: "/favicon-32x32.png"
  apple_touch_icon: "/apple-touch-icon.png"
comments: true
