baseURL = 'https://blog.lookscanned.io/'
languageCode = 'en'
title = 'Look Scanned Blog'
theme = 'PaperMod'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[params]
  displayFullLangName = true

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    title = 'Look Scanned Blog'
  [languages.zh]
    languageName = '简体中文'
    title = 'Look Scanned 博客'
  [languages.zh-tw]
    languageCode = 'zh-TW'
    languageName = '繁體中文'
    title = 'Look Scanned 部落格'
  [languages.de]
    languageName = 'Deutsch'
    title = 'Look Scanned Blog'
  [languages.es]
    languageName = 'Español'
    title = 'Blog de Look Scanned'
  [languages.fr]
    languageName = 'Français'
    title = 'Blog Look Scanned'
  [languages.it]
    languageName = 'Italiano'
    title = 'Blog di Look Scanned'
  [languages.ja]
    languageName = '日本語'
    title = 'Look Scanned ブログ'
  [languages.ko]
    languageName = '한국어'
    title = 'Look Scanned 블로그'
  [languages.ru]
    languageName = 'Русский'
    title = 'Блог Look Scanned'
  [languages.pt]
    languageName = 'Português'
    title = 'Blog do Look Scanned'
  [languages.ar]
    languageDirection = 'rtl'
    languageName = 'العربية'
    title = 'مدونة Look Scanned'
  [languages.hi]
    languageName = 'हिन्दी'
    title = 'Look Scanned ब्लॉग'
  [languages.tr]
    languageName = 'Türkçe'
    title = 'Look Scanned Blogu'
  [languages.nl]
    languageName = 'Nederlands'
    title = 'Look Scanned Blog'
  [languages.sv]
    languageName = 'Svenska'
    title = 'Look Scanned Blogg'
  [languages.pl]
    languageName = 'Polski'
    title = 'Blog Look Scanned'
  [languages.vi]
    languageName = 'Tiếng Việt'
    title = 'Blog Look Scanned'
  [languages.th]
    languageName = 'ไทย'
    title = 'บล็อก Look Scanned'
  [languages.id]
    languageName = 'Bahasa Indonesia'
    title = 'Blog Look Scanned'
  [languages.he]
    languageDirection = 'rtl'
    languageName = 'עברית'
    title = 'בלוג Look Scanned'
  [languages.ms]
    languageName = 'Bahasa Melayu'
    title = 'Blog Look Scanned'
  [languages.no]
    languageName = 'Norsk'
    title = 'Look Scanned Blogg'
