// AUTO-GENERATED by scripts/build-i18n.mjs from config/_default/languages.yml.
// Re-run that script after editing the source YAML to regenerate this file.

export interface MenuItem {
  name: string;
  url: string;
  weight: number | null;
}

export interface LocaleData {
  code: string;
  languageName: string;
  title: string;
  description: string;
  homeTitle: string;
  homeContent: string;
  menu: MenuItem[];
}

export const LOCALE_DATA: Record<string, LocaleData> = {
  "en": {
    "code": "en",
    "languageName": "English",
    "title": "Look Scanned Blog",
    "description": "Notes on web development, PDF processing, and privacy-first tools — from the team behind Look Scanned.",
    "homeTitle": "Look Scanned Blog",
    "homeContent": "👋 Welcome to the Look Scanned Blog!\n- 📚 [**Look Scanned**](https://lookscanned.io) is a lightweight, browser-based application that simulates scanned PDF effects. It's designed with privacy in mind, allowing developers, designers, and anyone else to add authentic scanning effects to PDFs without the need for physical hardware.",
    "menu": [
      {
        "name": "Archive",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Search",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tags",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "zh": {
    "code": "zh",
    "languageName": "简体中文",
    "title": "Look Scanned 博客",
    "description": "网页开发、PDF 处理、隐私优先工具——来自 Look Scanned 团队的随手记。",
    "homeTitle": "Look Scanned 博客",
    "homeContent": "👋 欢迎来到 Look Scanned 博客！\n- 📚 [**Look Scanned**](https://lookscanned.io) 是一个轻量级的基于浏览器的应用程序，可以模拟扫描PDF效果。它注重隐私保护，让开发者、设计师和所有用户无需物理硬件即可为PDF添加真实的扫描效果。",
    "menu": [
      {
        "name": "归档",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "搜索",
        "url": "search",
        "weight": 10
      },
      {
        "name": "标签",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "zh-tw": {
    "code": "zh-tw",
    "languageName": "繁體中文",
    "title": "Look Scanned 部落格",
    "description": "網頁開發、PDF 處理、重視隱私的工具——來自 Look Scanned 團隊的隨手記。",
    "homeTitle": "Look Scanned 部落格",
    "homeContent": "👋 歡迎來到 Look Scanned 部落格！\n- 📚 [**Look Scanned**](https://lookscanned.io) 是一個輕量級的網頁應用程式，可以模擬掃描PDF效果。它注重隱私保護，讓開發者、設計師和所有使用者無需實體硬體即可為PDF添加真實的掃描效果。",
    "menu": [
      {
        "name": "歸檔",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "搜尋",
        "url": "search",
        "weight": 10
      },
      {
        "name": "標籤",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "es": {
    "code": "es",
    "languageName": "Español",
    "title": "Blog de Look Scanned",
    "description": "Notas sobre desarrollo web, procesamiento de PDF y herramientas que respetan la privacidad — del equipo de Look Scanned.",
    "homeTitle": "Blog de Look Scanned",
    "homeContent": "👋 ¡Bienvenido al Blog de Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) es una aplicación ligera basada en navegador que simula efectos de PDF escaneado. Está diseñada pensando en la privacidad, permitiendo a desarrolladores, diseñadores y cualquier usuario añadir efectos de escaneo auténticos a PDFs sin necesidad de hardware físico.",
    "menu": [
      {
        "name": "Archivo",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Buscar",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Etiquetas",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "hi": {
    "code": "hi",
    "languageName": "हिन्दी",
    "title": "Look Scanned ब्लॉग",
    "description": "वेब डेवलपमेंट, PDF प्रोसेसिंग और प्राइवेसी-फर्स्ट टूल्स पर Look Scanned टीम के नोट्स।",
    "homeTitle": "Look Scanned ब्लॉग",
    "homeContent": "👋 Look Scanned ब्लॉग में आपका स्वागत है!\n- 📚 [**Look Scanned**](https://lookscanned.io) एक हल्का, ब्राउज़र-आधारित एप्लिकेशन है जो स्कैन किए गए PDF प्रभावों का अनुकरण करता है। यह गोपनीयता को ध्यान में रखकर डिज़ाइन किया गया है, जो डेवलपर्स, डिज़ाइनर्स और अन्य सभी को बिना किसी भौतिक हार्डवेयर के PDF में प्रामाणिक स्कैनिंग प्रभाव जोड़ने की सुविधा देता है।",
    "menu": [
      {
        "name": "पुरालेख",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "खोज",
        "url": "search",
        "weight": 10
      },
      {
        "name": "टैग",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "ar": {
    "code": "ar",
    "languageName": "العربية",
    "title": "مدونة Look Scanned",
    "description": "ملاحظات حول تطوير الويب ومعالجة PDF والأدوات التي تحترم الخصوصية — من فريق Look Scanned.",
    "homeTitle": "مدونة Look Scanned",
    "homeContent": "👋 مرحباً بكم في مدونة Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) هو تطبيق خفيف يعمل على المتصفح ويحاكي تأثيرات مسح PDF الضوئي. تم تصميمه مع مراعاة الخصوصية، مما يتيح للمطورين والمصممين وأي شخص آخر إضافة تأثيرات مسح ضوئي حقيقية إلى ملفات PDF دون الحاجة إلى أجهزة فعلية.",
    "menu": [
      {
        "name": "الأرشيف",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "بحث",
        "url": "search",
        "weight": 10
      },
      {
        "name": "الوسوم",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "fr": {
    "code": "fr",
    "languageName": "Français",
    "title": "Blog Look Scanned",
    "description": "Notes sur le développement web, le traitement de PDF et les outils respectueux de la vie privée — par l'équipe Look Scanned.",
    "homeTitle": "Blog Look Scanned",
    "homeContent": "👋 Bienvenue sur le Blog Look Scanned !\n- 📚 [**Look Scanned**](https://lookscanned.io) est une application légère basée sur navigateur qui simule des effets de PDF numérisé. Conçue dans le respect de la confidentialité, elle permet aux développeurs, designers et à tous les utilisateurs d'ajouter des effets de numérisation authentiques aux PDF sans matériel physique.",
    "menu": [
      {
        "name": "Archives",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Rechercher",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tags",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "pt": {
    "code": "pt",
    "languageName": "Português",
    "title": "Blog do Look Scanned",
    "description": "Notas sobre desenvolvimento web, processamento de PDF e ferramentas com foco em privacidade — da equipe do Look Scanned.",
    "homeTitle": "Blog do Look Scanned",
    "homeContent": "👋 Bem-vindo ao Blog do Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) é uma aplicação leve baseada em navegador que simula efeitos de PDF digitalizado. Foi projetada com foco na privacidade, permitindo que desenvolvedores, designers e qualquer pessoa adicione efeitos autênticos de digitalização a PDFs sem necessidade de hardware físico.",
    "menu": [
      {
        "name": "Arquivo",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Pesquisar",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tags",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "ja": {
    "code": "ja",
    "languageName": "日本語",
    "title": "Look Scanned ブログ",
    "description": "Web 開発、PDF 処理、プライバシー重視のツールについて — Look Scanned チームのノート。",
    "homeTitle": "Look Scanned ブログ",
    "homeContent": "👋 Look Scanned ブログへようこそ！\n- 📚 [**Look Scanned**](https://lookscanned.io) は、スキャンしたPDFの効果をシミュレートするブラウザベースの軽量アプリケーションです。プライバシーを重視して設計されており、開発者やデザイナー、その他すべてのユーザーが物理的なハードウェアを必要とせずに、PDFに本物のスキャン効果を追加できます。",
    "menu": [
      {
        "name": "アーカイブ",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "検索",
        "url": "search",
        "weight": 10
      },
      {
        "name": "タグ",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "de": {
    "code": "de",
    "languageName": "Deutsch",
    "title": "Look Scanned Blog",
    "description": "Notizen zu Webentwicklung, PDF-Verarbeitung und datenschutzorientierten Tools — vom Team hinter Look Scanned.",
    "homeTitle": "Look Scanned Blog",
    "homeContent": "👋 Willkommen beim Look Scanned Blog!\n- 📚 [**Look Scanned**](https://lookscanned.io) ist eine schlanke, browserbasierte Anwendung, die PDF-Scan-Effekte simuliert. Sie wurde mit Fokus auf Datenschutz entwickelt und ermöglicht es Entwicklern, Designern und allen anderen, authentische Scan-Effekte zu PDFs hinzuzufügen – ganz ohne physische Hardware.",
    "menu": [
      {
        "name": "Archiv",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Suche",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tags",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "ru": {
    "code": "ru",
    "languageName": "Русский",
    "title": "Блог Look Scanned",
    "description": "Заметки о веб-разработке, обработке PDF и инструментах, уважающих приватность — от команды Look Scanned.",
    "homeTitle": "Блог Look Scanned",
    "homeContent": "👋 Добро пожаловать в блог Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) - это легкое браузерное приложение, которое имитирует эффекты сканированных PDF. Оно разработано с учетом конфиденциальности, позволяя разработчикам, дизайнерам и всем желающим добавлять реалистичные эффекты сканирования в PDF без необходимости в физическом оборудовании.",
    "menu": [
      {
        "name": "Архив",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Поиск",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Теги",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "id": {
    "code": "id",
    "languageName": "Bahasa Indonesia",
    "title": "Blog Look Scanned",
    "description": "Catatan tentang pengembangan web, pemrosesan PDF, dan alat yang mengutamakan privasi — dari tim Look Scanned.",
    "homeTitle": "Blog Look Scanned",
    "homeContent": "👋 Selamat datang di Blog Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) adalah aplikasi berbasis browser yang ringan yang mensimulasikan efek PDF hasil pemindaian. Dirancang dengan memperhatikan privasi, memungkinkan pengembang, desainer, dan siapa saja untuk menambahkan efek pemindaian yang autentik ke PDF tanpa memerlukan perangkat keras fisik.",
    "menu": [
      {
        "name": "Arsip",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Cari",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tag",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "ko": {
    "code": "ko",
    "languageName": "한국어",
    "title": "Look Scanned 블로그",
    "description": "웹 개발, PDF 처리, 프라이버시 우선 도구에 관한 Look Scanned 팀의 기록.",
    "homeTitle": "Look Scanned 블로그",
    "homeContent": "👋 Look Scanned 블로그에 오신 것을 환영합니다!\n- 📚 [**Look Scanned**](https://lookscanned.io)은 스캔된 PDF 효과를 시뮬레이션하는 경량 브라우저 기반 애플리케이션입니다. 개인정보 보호를 고려하여 설계되었으며, 개발자, 디자이너 및 모든 사용자가 물리적 하드웨어 없이도 PDF에 실제 스캔 효과를 추가할 수 있습니다.",
    "menu": [
      {
        "name": "아카이브",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "검색",
        "url": "search",
        "weight": 10
      },
      {
        "name": "태그",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "it": {
    "code": "it",
    "languageName": "Italiano",
    "title": "Blog di Look Scanned",
    "description": "Note su sviluppo web, elaborazione PDF e strumenti che rispettano la privacy — dal team di Look Scanned.",
    "homeTitle": "Blog di Look Scanned",
    "homeContent": "👋 Benvenuto nel Blog di Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) è un'applicazione leggera basata su browser che simula effetti di scansione PDF. È progettata pensando alla privacy, permettendo a sviluppatori, designer e chiunque altro di aggiungere autentici effetti di scansione ai PDF senza bisogno di hardware fisico.",
    "menu": [
      {
        "name": "Archivio",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Cerca",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tag",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "tr": {
    "code": "tr",
    "languageName": "Türkçe",
    "title": "Look Scanned Blogu",
    "description": "Web geliştirme, PDF işleme ve gizliliği önceleyen araçlar üzerine — Look Scanned ekibinin notları.",
    "homeTitle": "Look Scanned Blogu",
    "homeContent": "👋 Look Scanned Blogu'na hoş geldiniz!\n- 📚 [**Look Scanned**](https://lookscanned.io), taranmış PDF efektlerini simüle eden hafif, tarayıcı tabanlı bir uygulamadır. Gizlilik göz önünde bulundurularak tasarlanmış olup, geliştiricilerin, tasarımcıların ve diğer herkesin fiziksel donanıma ihtiyaç duymadan PDF'lere gerçek tarama efektleri eklemesine olanak tanır.",
    "menu": [
      {
        "name": "Arşiv",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Ara",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Etiketler",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "pl": {
    "code": "pl",
    "languageName": "Polski",
    "title": "Blog Look Scanned",
    "description": "Notatki o tworzeniu stron, przetwarzaniu PDF i narzędziach szanujących prywatność — od zespołu Look Scanned.",
    "homeTitle": "Blog Look Scanned",
    "homeContent": "👋 Witamy na blogu Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) to lekka aplikacja przeglądarkowa, która symuluje efekty skanowania PDF. Została zaprojektowana z myślą o prywatności, umożliwiając programistom, projektantom i wszystkim innym dodawanie autentycznych efektów skanowania do plików PDF bez potrzeby posiadania fizycznego sprzętu.",
    "menu": [
      {
        "name": "Archiwum",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Szukaj",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tagi",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "nl": {
    "code": "nl",
    "languageName": "Nederlands",
    "title": "Look Scanned Blog",
    "description": "Notities over webontwikkeling, PDF-verwerking en privacyvriendelijke tools — van het Look Scanned-team.",
    "homeTitle": "Look Scanned Blog",
    "homeContent": "👋 Welkom bij de Look Scanned Blog!\n- 📚 [**Look Scanned**](https://lookscanned.io) is een lichtgewicht, browser-gebaseerde applicatie die gescande PDF-effecten simuleert. Het is ontworpen met privacy in gedachten, waardoor ontwikkelaars, designers en iedereen authentieke scan-effecten aan PDF's kan toevoegen zonder fysieke hardware.",
    "menu": [
      {
        "name": "Archief",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Zoeken",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tags",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "vi": {
    "code": "vi",
    "languageName": "Tiếng Việt",
    "title": "Blog Look Scanned",
    "description": "Ghi chú về phát triển web, xử lý PDF và công cụ ưu tiên quyền riêng tư — từ đội ngũ Look Scanned.",
    "homeTitle": "Blog Look Scanned",
    "homeContent": "👋 Chào mừng đến với Blog Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) là một ứng dụng nhẹ, chạy trên trình duyệt cho phép mô phỏng hiệu ứng PDF được quét. Được thiết kế với việc bảo mật quyền riêng tư, cho phép các nhà phát triển, nhà thiết kế và bất kỳ ai thêm hiệu ứng quét chân thực vào PDF mà không cần thiết bị phần cứng.",
    "menu": [
      {
        "name": "Lưu trữ",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Tìm kiếm",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Thẻ",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "th": {
    "code": "th",
    "languageName": "ไทย",
    "title": "บล็อก Look Scanned",
    "description": "บันทึกเรื่องการพัฒนาเว็บ การประมวลผล PDF และเครื่องมือที่เคารพความเป็นส่วนตัว — จากทีม Look Scanned",
    "homeTitle": "บล็อก Look Scanned",
    "homeContent": "👋 ยินดีต้อนรับสู่บล็อก Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) เป็นแอปพลิเคชันเบาๆ ที่ทำงานบนเบราว์เซอร์ซึ่งจำลองเอฟเฟกต์การสแกน PDF ออกแบบมาโดยคำนึงถึงความเป็นส่วนตัว ช่วยให้นักพัฒนา นักออกแบบ และทุกคนสามารถเพิ่มเอฟเฟกต์การสแกนที่เหมือนจริงลงใน PDF โดยไม่จำเป็นต้องใช้ฮาร์ดแวร์จริง",
    "menu": [
      {
        "name": "คลังเก็บ",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "ค้นหา",
        "url": "search",
        "weight": 10
      },
      {
        "name": "แท็ก",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "sv": {
    "code": "sv",
    "languageName": "Svenska",
    "title": "Look Scanned Blogg",
    "description": "Anteckningar om webbutveckling, PDF-bearbetning och integritetsvänliga verktyg — från Look Scanned-teamet.",
    "homeTitle": "Look Scanned Blogg",
    "homeContent": "👋 Välkommen till Look Scanned Bloggen!\n- 📚 [**Look Scanned**](https://lookscanned.io) är en lättviktig, webbläsarbaserad applikation som simulerar inskannade PDF-effekter. Den är designad med integritet i åtanke och låter utvecklare, designers och alla andra lägga till autentiska skanningseffekter till PDF:er utan behov av fysisk hårdvara.",
    "menu": [
      {
        "name": "Arkiv",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Sök",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Taggar",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "ms": {
    "code": "ms",
    "languageName": "Bahasa Melayu",
    "title": "Blog Look Scanned",
    "description": "Catatan tentang pembangunan web, pemprosesan PDF, dan alat yang mengutamakan privasi — daripada pasukan Look Scanned.",
    "homeTitle": "Blog Look Scanned",
    "homeContent": "👋 Selamat datang ke Blog Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) ialah aplikasi ringan berasaskan pelayar yang mensimulasikan kesan PDF yang diimbas. Ia direka dengan mengutamakan privasi, membolehkan pembangun, pereka dan sesiapa sahaja menambah kesan imbasan yang autentik kepada PDF tanpa memerlukan perkakasan fizikal.",
    "menu": [
      {
        "name": "Arkib",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Cari",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Tag",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "he": {
    "code": "he",
    "languageName": "עברית",
    "title": "בלוג Look Scanned",
    "description": "הערות על פיתוח אתרים, עיבוד PDF וכלים ששומרים על פרטיות — מצוות Look Scanned.",
    "homeTitle": "בלוג Look Scanned",
    "homeContent": "👋 ברוכים הבאים לבלוג Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) הוא יישום קל משקל מבוסס דפדפן המדמה אפקטים של PDF סרוק. הוא תוכנן תוך התחשבות בפרטיות, ומאפשר למפתחים, מעצבים וכל אחד אחר להוסיף אפקטים אותנטיים של סריקה לקבצי PDF ללא צורך בחומרה פיזית.",
    "menu": [
      {
        "name": "ארכיון",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "חיפוש",
        "url": "search",
        "weight": 10
      },
      {
        "name": "תגיות",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "cs": {
    "code": "cs",
    "languageName": "Čeština",
    "title": "Look Scanned Blog",
    "description": "Poznámky o vývoji webu, zpracování PDF a nástrojích respektujících soukromí — od týmu Look Scanned.",
    "homeTitle": "Look Scanned Blog",
    "homeContent": "👋 Vítejte na Look Scanned Blogu!\n- 📚 [**Look Scanned**](https://lookscanned.io) je lehká aplikace v prohlížeči, která simuluje efekty skenovaných PDF. Je navržena s důrazem na soukromí a umožňuje vývojářům, designérům i komukoli dalšímu přidávat autentické skenovací efekty do PDF bez fyzického hardwaru.",
    "menu": [
      {
        "name": "Archiv",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Hledat",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Štítky",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "hu": {
    "code": "hu",
    "languageName": "Magyar",
    "title": "Look Scanned Blog",
    "description": "Jegyzetek webfejlesztésről, PDF-feldolgozásról és adatvédelmet tisztelő eszközökről — a Look Scanned csapatától.",
    "homeTitle": "Look Scanned Blog",
    "homeContent": "👋 Üdv a Look Scanned Blogon!\n- 📚 [**Look Scanned**](https://lookscanned.io) egy könnyű, böngészőalapú alkalmazás, amely szkennelt PDF-hatásokat szimulál. Adatvédelemre tervezve lehetővé teszi, hogy fejlesztők, designerek és bárki valósághű szkennelési effekteket adjon a PDF-ekhez fizikai hardver nélkül.",
    "menu": [
      {
        "name": "Archívum",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Keresés",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Címkék",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "ro": {
    "code": "ro",
    "languageName": "Română",
    "title": "Blogul Look Scanned",
    "description": "Notițe despre dezvoltare web, procesare PDF și instrumente care respectă confidențialitatea — de la echipa Look Scanned.",
    "homeTitle": "Blogul Look Scanned",
    "homeContent": "👋 Bine ai venit pe Blogul Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) este o aplicație ușoară, bazată pe browser, care simulează efecte de PDF scanat. Proiectată cu atenție la confidențialitate, le permite dezvoltatorilor, designerilor și tuturor utilizatorilor să adauge efecte autentice fără hardware fizic.",
    "menu": [
      {
        "name": "Arhivă",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Căutare",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Etichete",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "el": {
    "code": "el",
    "languageName": "Ελληνικά",
    "title": "Ιστολόγιο Look Scanned",
    "description": "Σημειώσεις για την ανάπτυξη web, την επεξεργασία PDF και εργαλεία με σεβασμό στην ιδιωτικότητα — από την ομάδα του Look Scanned.",
    "homeTitle": "Ιστολόγιο Look Scanned",
    "homeContent": "👋 Καλώς ήρθατε στο Ιστολόγιο Look Scanned!\n- 📚 Το [**Look Scanned**](https://lookscanned.io) είναι μια ελαφριά εφαρμογή στον περιηγητή που προσομοιώνει εφέ σαρωμένων PDF. Σχεδιασμένη με γνώμονα την ιδιωτικότητα, επιτρέπει σε προγραμματιστές, σχεδιαστές και όλους τους χρήστες να προσθέτουν αυθεντικά εφέ χωρίς φυσικό υλικό.",
    "menu": [
      {
        "name": "Αρχείο",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Αναζήτηση",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Ετικέτες",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "uk": {
    "code": "uk",
    "languageName": "Українська",
    "title": "Блог Look Scanned",
    "description": "Нотатки про веброзробку, обробку PDF та інструменти, що поважають приватність — від команди Look Scanned.",
    "homeTitle": "Блог Look Scanned",
    "homeContent": "👋 Ласкаво просимо до блогу Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) – це легкий веб-додаток, що імітує ефекти сканованих PDF. Створений із повагою до приватності, він дозволяє додавати автентичні ефекти без потреби у фізичному обладнанні.",
    "menu": [
      {
        "name": "Архів",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Пошук",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Теги",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "fil": {
    "code": "fil",
    "languageName": "Filipino",
    "title": "Look Scanned Blog",
    "description": "Mga tala tungkol sa web development, pagpoproseso ng PDF, at mga tool na nagpapahalaga sa privacy — mula sa team ng Look Scanned.",
    "homeTitle": "Look Scanned Blog",
    "homeContent": "👋 Maligayang pagdating sa Look Scanned Blog!\n- 📚 Ang [**Look Scanned**](https://lookscanned.io) ay isang magaan na browser-based na app na nagsi-simulate ng mga efektong parang na-scan na PDF. Dinisenyo na may pokus sa privacy para makapagdagdag ng tunay na scan effects sa PDF nang walang physical na hardware.",
    "menu": [
      {
        "name": "Arkibo",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Paghahanap",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Mga Tag",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "bn": {
    "code": "bn",
    "languageName": "বাংলা",
    "title": "Look Scanned ব্লগ",
    "description": "ওয়েব ডেভেলপমেন্ট, PDF প্রসেসিং এবং গোপনীয়তা-কেন্দ্রিক টুল নিয়ে — Look Scanned টিমের নোট।",
    "homeTitle": "Look Scanned ব্লগ",
    "homeContent": "👋 Look Scanned ব্লগে স্বাগতম!\n- 📚 [**Look Scanned**](https://lookscanned.io) একটি হালকা, ব্রাউজার-ভিত্তিক অ্যাপ যা স্ক্যান করা PDF-এর প্রভাব অনুকরণ করে। গোপনীয়তা বিবেচনায় রেখে তৈরি, যা ডেভেলপার, ডিজাইনার এবং সবার জন্য হার্ডওয়্যার ছাড়াই PDF-এ বাস্তবসম্মত স্ক্যানিং এফেক্ট যোগ করতে দেয়।",
    "menu": [
      {
        "name": "সংরক্ষণাগার",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "অনুসন্ধান",
        "url": "search",
        "weight": 10
      },
      {
        "name": "ট্যাগ",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "ur": {
    "code": "ur",
    "languageName": "اردو",
    "title": "Look Scanned بلاگ",
    "description": "ویب ڈویلپمنٹ، PDF پراسیسنگ، اور پرائیویسی پر مرکوز ٹولز پر — Look Scanned ٹیم کے نوٹس۔",
    "homeTitle": "Look Scanned بلاگ",
    "homeContent": "👋 Look Scanned بلاگ میں خوش آمدید!\n- 📚 [**Look Scanned**](https://lookscanned.io) ایک ہلکی، براؤزر پر مبنی ایپ ہے جو اسکین شدہ PDF کے اثرات کی نقل کرتی ہے۔ پرائیویسی کو مدِنظر رکھتے ہوئے ڈیزائن کی گئی، یہ ڈیولپرز، ڈیزائنرز اور ہر کسی کو بغیر فزیکل ہارڈویئر کے PDF میں مستند اسکیننگ ایفیکٹس شامل کرنے دیتی ہے۔",
    "menu": [
      {
        "name": "محفوظات",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "تلاش",
        "url": "search",
        "weight": 10
      },
      {
        "name": "ٹیگز",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "sw": {
    "code": "sw",
    "languageName": "Kiswahili",
    "title": "Blogu ya Look Scanned",
    "description": "Maelezo kuhusu uundaji wa wavuti, uchakataji wa PDF, na zana zinazoheshimu faragha — kutoka kwa timu ya Look Scanned.",
    "homeTitle": "Blogu ya Look Scanned",
    "homeContent": "👋 Karibu kwenye Blogu ya Look Scanned!\n- 📚 [**Look Scanned**](https://lookscanned.io) ni programu nyepesi inayotumia kivinjari inayosimulate athari za PDF iliyoskanishwa. Imetengenezwa kwa kuzingatia faragha ili kuruhusu wabunifu, wasanifu na mtu yeyote kuongeza athari halisi kwenye PDF bila vifaa vya kimwili.",
    "menu": [
      {
        "name": "Kumbukumbu",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Tafuta",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Lebo",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
  "af": {
    "code": "af",
    "languageName": "Afrikaans",
    "title": "Look Scanned Blog",
    "description": "Notas oor webontwikkeling, PDF-verwerking en privaatheidsgesentreerde gereedskap — van die Look Scanned-span.",
    "homeTitle": "Look Scanned Blog",
    "homeContent": "👋 Welkom by die Look Scanned-blog!\n- 📚 [**Look Scanned**](https://lookscanned.io) is ’n liggewig, blaaiergebaseerde toepassing wat geskendeerde PDF-effekte simuleer. Dit is met privaatheid in gedagte ontwerp en stel ontwikkelaars, ontwerpers en enigiemand anders in staat om outentieke effekte by PDF’s te voeg sonder fisiese hardeware.",
    "menu": [
      {
        "name": "Argief",
        "url": "archives",
        "weight": 5
      },
      {
        "name": "Soek",
        "url": "search",
        "weight": 10
      },
      {
        "name": "Etikette",
        "url": "tags",
        "weight": 15
      },
      {
        "name": "Look Scanned",
        "url": "https://lookscanned.io",
        "weight": null
      }
    ]
  },
};
