/**
 * Generate src/i18n/locales.ts and src/i18n/ui.ts from Hugo's existing YAML.
 *
 * Sources:
 *   - config/_default/languages.yml         (per-locale site metadata)
 *   - themes/PaperMod/i18n/<locale>.yaml    (UI string translations)
 *
 * Re-run after editing either source. The generated TS modules drive every
 * Astro page that needs a translated string.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const LANGUAGES_YML = resolve(ROOT, "config/_default/languages.yml");
const PAPERMOD_DIR = resolve(ROOT, "themes/PaperMod/i18n");
const OUT_LOCALES = resolve(ROOT, "src/i18n/locales.ts");
const OUT_UI = resolve(ROOT, "src/i18n/ui.ts");

// Canonical locale order — must match src/i18n/locales.config.mjs.
const LOCALE_ORDER = [
  "en", "zh", "zh-tw", "es", "hi", "ar", "fr", "pt", "ja", "de",
  "ru", "id", "ko", "it", "tr", "pl", "nl", "vi", "th", "sv",
  "ms", "he", "cs", "hu", "ro", "el", "uk", "fil", "bn", "ur",
  "sw", "af",
];

function readYaml(path) {
  return parseYaml(readFileSync(path, "utf8"));
}

function trimContent(s) {
  if (!s) return "";
  // Hugo's `>` folded YAML scalar leaves a trailing newline.
  return String(s).replace(/\n+$/g, "").trim();
}

function buildLocale(code, raw) {
  if (!raw) {
    throw new Error(`locales.yml missing locale: ${code}`);
  }
  const menuItems = (raw.menu?.main ?? []).map((item) => ({
    name: item.name ?? "",
    url: item.url ?? "",
    weight: typeof item.weight === "number" ? item.weight : null,
  }));
  return {
    code,
    languageName: raw.languageName ?? code,
    title: raw.title ?? "Look Scanned Blog",
    description: raw.params?.description ?? "",
    homeTitle: raw.params?.homeInfoParams?.Title ?? "",
    homeContent: trimContent(raw.params?.homeInfoParams?.Content),
    menu: menuItems,
  };
}

function emitLocales(allLocales) {
  const lines = [
    "// AUTO-GENERATED by scripts/build-i18n.mjs from config/_default/languages.yml.",
    "// Re-run that script after editing the source YAML to regenerate this file.",
    "",
    "export interface MenuItem {",
    "  name: string;",
    "  url: string;",
    "  weight: number | null;",
    "}",
    "",
    "export interface LocaleData {",
    "  code: string;",
    "  languageName: string;",
    "  title: string;",
    "  description: string;",
    "  homeTitle: string;",
    "  homeContent: string;",
    "  menu: MenuItem[];",
    "}",
    "",
    "export const LOCALE_DATA: Record<string, LocaleData> = {",
  ];
  for (const code of LOCALE_ORDER) {
    const data = allLocales[code];
    const body = JSON.stringify(data, null, 2)
      .split("\n")
      .map((l, i) => (i === 0 ? l : "  " + l))
      .join("\n");
    lines.push(`  ${JSON.stringify(code)}: ${body},`);
  }
  lines.push("};", "");
  return lines.join("\n");
}

function emitUi(allUi) {
  const lines = [
    "// AUTO-GENERATED by scripts/build-i18n.mjs from themes/PaperMod/i18n/*.yaml.",
    "// Re-run that script after editing the source YAML to regenerate this file.",
    "// Locales missing from PaperMod fall back to English strings.",
    "",
    "export interface UIStrings {",
    "  prev_page: string;",
    "  next_page: string;",
    "  toc: string;",
    "  translations: string;",
    "  home: string;",
    "  edit_post: string;",
    "  code_copy: string;",
    "  code_copied: string;",
    "  read_time_one: string;",
    "  read_time_other: string;",
    "  words_one: string;",
    "  words_other: string;",
    "}",
    "",
    "export const UI: Record<string, UIStrings> = {",
  ];
  const en = allUi.en;
  for (const code of LOCALE_ORDER) {
    const d = allUi[code] ?? {};
    const pick = (key) => {
      const v = d[key];
      return typeof v === "string" ? v : (typeof en[key] === "string" ? en[key] : "");
    };
    const pickPlural = (key, form) => {
      const v = d[key];
      if (v && typeof v === "object" && v[form]) return v[form];
      const ev = en[key];
      return ev && typeof ev === "object" && ev[form] ? ev[form] : "";
    };
    const entry = {
      prev_page: pick("prev_page"),
      next_page: pick("next_page"),
      toc: pick("toc"),
      translations: pick("translations"),
      home: pick("home"),
      edit_post: pick("edit_post"),
      code_copy: pick("code_copy"),
      code_copied: pick("code_copied"),
      read_time_one: pickPlural("read_time", "one"),
      read_time_other: pickPlural("read_time", "other"),
      words_one: pickPlural("words", "one"),
      words_other: pickPlural("words", "other"),
    };
    const body = JSON.stringify(entry, null, 2)
      .split("\n")
      .map((l, i) => (i === 0 ? l : "  " + l))
      .join("\n");
    lines.push(`  ${JSON.stringify(code)}: ${body},`);
  }
  lines.push("};", "");
  return lines.join("\n");
}

function parsePapermodFile(path) {
  // PaperMod stores translations as an array of { id, translation } objects.
  const arr = parseYaml(readFileSync(path, "utf8"));
  const out = {};
  for (const item of arr ?? []) {
    out[item.id] = item.translation;
  }
  return out;
}

function main() {
  const langData = readYaml(LANGUAGES_YML);
  const localesOut = {};
  for (const code of LOCALE_ORDER) {
    localesOut[code] = buildLocale(code, langData[code]);
  }
  writeFileSync(OUT_LOCALES, emitLocales(localesOut));
  console.log(`wrote ${OUT_LOCALES} (${LOCALE_ORDER.length} locales)`);

  const uiOut = {};
  const missing = [];
  for (const code of LOCALE_ORDER) {
    const file = resolve(PAPERMOD_DIR, `${code}.yaml`);
    if (!existsSync(file)) {
      missing.push(code);
      continue;
    }
    uiOut[code] = parsePapermodFile(file);
  }
  if (!uiOut.en) {
    throw new Error("PaperMod en.yaml missing — cannot build fallback strings");
  }
  writeFileSync(OUT_UI, emitUi(uiOut));
  console.log(
    `wrote ${OUT_UI} (${LOCALE_ORDER.length - missing.length} translated, ${missing.length} EN fallback: ${missing.join(", ") || "—"})`,
  );
}

main();
