name: Save to Wayback Machine

on:
  push:

permissions:
  contents: read

jobs:
  save:

    runs-on: ubuntu-latest

    steps:
    - name: Save to Wayback Machine
      uses: JamieMagee/wayback@v2.0.0
      with:
        url: |-
          https://blog.lookscanned.io
          https://blog.lookscanned.io/zh/
          https://blog.lookscanned.io/zh-tw/
          https://blog.lookscanned.io/de/
          https://blog.lookscanned.io/es/
          https://blog.lookscanned.io/fr/
          https://blog.lookscanned.io/it/
          https://blog.lookscanned.io/ja/
          https://blog.lookscanned.io/ko/
          https://blog.lookscanned.io/ru/
          https://blog.lookscanned.io/pt/
          https://blog.lookscanned.io/ar/
          https://blog.lookscanned.io/hi/
          https://blog.lookscanned.io/tr/
          https://blog.lookscanned.io/nl/
          https://blog.lookscanned.io/sv/
          https://blog.lookscanned.io/pl/
          https://blog.lookscanned.io/vi/
          https://blog.lookscanned.io/th/
          https://blog.lookscanned.io/id/
          https://blog.lookscanned.io/he/
          https://blog.lookscanned.io/zh/archives/
          https://blog.lookscanned.io/zh-tw/archives/
          https://blog.lookscanned.io/de/archives/
          https://blog.lookscanned.io/es/archives/
          https://blog.lookscanned.io/fr/archives/
          https://blog.lookscanned.io/it/archives/
          https://blog.lookscanned.io/ja/archives/
          https://blog.lookscanned.io/ko/archives/
          https://blog.lookscanned.io/ru/archives/
          https://blog.lookscanned.io/pt/archives/
          https://blog.lookscanned.io/ar/archives/
          https://blog.lookscanned.io/hi/archives/
          https://blog.lookscanned.io/tr/archives/
          https://blog.lookscanned.io/nl/archives/
          https://blog.lookscanned.io/sv/archives/
          https://blog.lookscanned.io/pl/archives/
          https://blog.lookscanned.io/vi/archives/
          https://blog.lookscanned.io/th/archives/
          https://blog.lookscanned.io/id/archives/
          https://blog.lookscanned.io/he/archives/
          https://blog.lookscanned.io/ms/archives/
        saveErrors: false
        saveOutlinks: true
        saveScreenshot: true
