name: Save to Wayback Machine

on:
  push:

permissions:
  contents: read

jobs:
  save:

    runs-on: ubuntu-latest

    steps:
    - name: Save to Wayback Machine
      uses: JamieMagee/wayback@v2.0.0
      with:
        url: |-
          https://blog.lookscanned.io
          https://blog.lookscanned.io/zh/
        saveErrors: false
        saveOutlinks: true
        saveScreenshot: true
